'use client';
import HealthContextProvider from '@/app/contexts/HealthContext';
import HungerContextProvider from '@/app/contexts/HungerContext';
import MotivationContextProvider from '@/app/contexts/MotivationContext';
import IQContextProvider from '@/app/contexts/IqContext';
import './globals.css'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HealthContextProvider>
          <HungerContextProvider>
            <MotivationContextProvider>
              <IQContextProvider> 
                {children}
              </IQContextProvider>
            </MotivationContextProvider>
          </HungerContextProvider>
        </HealthContextProvider>
      </body>
    </html>
  )
}
